{% set name = "lbdiracwrappers" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/LbDiracWrappers-{{ version }}.tar.gz
  sha256: 6e54527bcc92f789fbc8a0dd67668d1738421f449207103793288710853f1efc

build:
  number: 0
  noarch: python
  entry_points:
    - lb-dirac=LbDiracWrappers:lb_dirac
    - lhcb-proxy-init=LbDiracWrappers:lhcb_proxy_init
    - lhcb-proxy-info=LbDiracWrappers:lhcb_proxy_info
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - lbenv
    - python >=3.6
    - packaging >=20.0

test:
  imports:
    - LbDiracWrappers
  commands:
    - pip check
    - lb-dirac --help
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb-core/lbdiracwrappers
  summary: Wrappers for LHCbDirac commands
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bcouturi
    - chrisburr
